services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sam-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env.development
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - sam

volumes:
  node_modules:

networks:
  sam:
    name: sam
    external: false
